// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaUDSPM_p2xRrxL4qCYFrta_j-rhj0sx0',
    appId: '1:169073302535:web:5d0978b319c5d7b0261ea2',
    messagingSenderId: '169073302535',
    projectId: 'projectmehema',
    authDomain: 'projectmehema.firebaseapp.com',
    storageBucket: 'projectmehema.appspot.com',
    measurementId: 'G-D5ESRX3HJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbu6M7uXtrdd9VKgPa80hTIlY_a7_29jc',
    appId: '1:169073302535:android:bdb172566a9432a1261ea2',
    messagingSenderId: '169073302535',
    projectId: 'projectmehema',
    storageBucket: 'projectmehema.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXKZwd8-yNbRjNOi1YgCu4wcXMkLUWoUs',
    appId: '1:169073302535:ios:4b26ba3f062ad509261ea2',
    messagingSenderId: '169073302535',
    projectId: 'projectmehema',
    storageBucket: 'projectmehema.appspot.com',
    iosBundleId: 'com.example.projectmehema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXKZwd8-yNbRjNOi1YgCu4wcXMkLUWoUs',
    appId: '1:169073302535:ios:bf089ae314ccc931261ea2',
    messagingSenderId: '169073302535',
    projectId: 'projectmehema',
    storageBucket: 'projectmehema.appspot.com',
    iosBundleId: 'com.example.projectmehema.RunnerTests',
  );
}
